#ifndef CONSTANTS_H
#define CONSTANTS_H

enum
{
    CHAR_SIZE = 8,
    SCREEN_WIDTH = 400,
    SCREEN_HEIGHT = 300,
    SCREEN_WIDTH_CHAR = SCREEN_WIDTH / CHAR_SIZE,
    SCREEN_HEIGHT_CHAR = SCREEN_HEIGHT / CHAR_SIZE
};

enum
{
    CHAR_BACKGROUND=0,
    CHAR_FILL,
    CHAR_TOPBAR,

    CHAR_LINE_VERT=128, // Start after fonts
    CHAR_LINE_HORIZ,
    CHAR_LINE_VERT_MARKED,
    CHAR_LINE_HORIZ_MARKED,
    CHAR_CORNER_TOP_LEFT,
    CHAR_CORNER_TOP_RIGHT,
    CHAR_CORNER_TOP_LEFT_MARKED,
    CHAR_CORNER_TOP_RIGHT_MARKED,
    CHAR_CORNER_BOTTOM_LEFT,
    CHAR_CORNER_BOTTOM_RIGHT,
    CHAR_CORNER_BOTTOM_LEFT_MARKED,
    CHAR_CORNER_BOTTOM_RIGHT_MARKED,
    CHAR_TEE_VERT_LEFT,
    CHAR_TEE_VERT_RIGHT,
    CHAR_TEE_VERT_LEFT_MARKED,
    CHAR_TEE_VERT_RIGHT_MARKED,
    CHAR_TEE_HORIZ_TOP,
    CHAR_TEE_HORIZ_TOP_MARKED,
    CHAR_CROSS,
    CHAR_CROSS_MARKED,
    CHAR_TEE_HORIZ_BOTTOM,
    CHAR_TEE_HORIZ_BOTTOM_MARKED
};

#endif // CONSTANTS_H
